[project]
name = "custom title bar"
version = "0.1.0"
description = "A Custom Title Bar"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
  "flet==0.25.0"
]

product = "Custom Title Bar"

[tool.flet.app]
path = "src"